version: 1

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION_PLACEHOLDER>"
        LoadBalancerInfo:
          ContainerName: webgoat-container
          ContainerPort: 8080

DeploymentConfiguration:
  MaximumPercent: 200
  MinimumHealthyPercent: 100

TrafficRoutingConfig:
  Type: TimeBasedCanary
  TimeBasedCanary:
    interval: 1
    percentage: 100

Hooks:
  AfterAllowTestTraffic:
    - location: scripts/validate.sh
      timeout: 180
      runas: root
