version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION_PLACEHOLDER>
        LoadBalancerInfo:
          ContainerName: webgoat-container  # ❗ 컨테이너 이름 (taskdef.json과 일치해야 함)
          ContainerPort: 8080               # ❗ 컨테이너가 노출하는 포트
DeploymentConfiguration:
  MaximumPercent: 200
  MinimumHealthyPercent: 100
TrafficRoutingConfig:
  Type: AllAtOnce  # 또는 TimeBasedCanary / TimeBasedLinear
